### ISSUE TITLE
Website link is broken

### ISSUE THREAD

**Issue by EtiennePerot** [technoweenie/cronwtf#3]
Website link on https://github.com/technoweenie/cronwtf
- Currently links to http://cronwtf.com/
- Should link to http://cronwtf.github.com/

**Comment by sunny** [comment]
http://cronwtf.github.io/ actually.

**Comment by M1ke** [comment]
Still broken too, now goes to some spam site.

**Comment by CoolOppo** [comment]
![](https://visionless.me/u/y35994.png)

:(

**Comment by technoweenie** [comment]
It's at https://cronwtf.dev now.
