### ISSUE TITLE
month is wrong; doesn't like leading zeros

### ISSUE THREAD

**Issue by NatureMuncher** [technoweenie/cronwtf#7]
05 03 25 06 06 results in error
05 03 25 6 6 results in Jul instead of Jun

**Comment by priyankt68** [comment]
For the error mentioned for months, it is fixed in [this](https://github.com/technoweenie/cronwtf/commit/a80f06f0605fe0b60195a2f698c023379f01d648?diff=split) commit.

You may fork the latest version and try it locally. It's incorrect in the website.

**Comment by technoweenie** [comment]
The fix is live on https://cronwtf.dev now.
